default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  url: postgresql://pguser:pgpassword@postgres/provisioner_development


test:
  <<: *default
  url: postgresql://pguser:pgpassword@postgres/provisioner_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
