# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 696949403be61ade83db9dbea1219fa90af027ea0fda2b9084821b43a42b24b30c8304f45455e8ce7a3f891dd17c9ebfae1a1cc83e25a7e44c98eccc12452bf9

test:
  secret_key_base: 4272062b9dd81b1b0315d7bbb2ec0882474f174b320bdd638621581e6a3efc4b8010c25db0e5b0f88add05d6b022a92c8dc41c1e3477cd69ed7e2cda397cd01d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
